name: Test

on:
  push:
    branches:
      - '*'
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Lint
        run: |
          flake8 magic_filter
          isort --check-only -df magic_filter
          black --check --diff magic_filter

      - name: mypy
        run: mypy magic_filter

      - name: Test
        run: |
          pytest --cov=magic_filter --cov-config .coveragerc --cov-report=xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          name: py-${{ matrix.python-version }}-${{ matrix.os }}
          fail_ci_if_error: true

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U pip virtualenv
          pip install poetry
          poetry config virtualenvs.create false

      - name: Build
        run: |
          poetry build

      - name: Try install wheel
        run: |
          mkdir -p try_install
          cd try_install
          virtualenv venv
          venv/bin/pip install ../dist/magic_filter-*.whl
          venv/bin/python -c "import magic_filter; print(magic_filter)"

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist/*
